In [11]:
import numpy as np
import pandas as pd
import os
import glob

In [12]:
path = os.getcwd()
home_path = os.path.dirname(path)
data_folder = f'{home_path}\\Data'

In [15]:
files = glob.glob(f"{data_folder}\\*.txt")
files

['C:\\Users\\david\\Documents\\@@ Python\\Jaar 5\\Q3\\ENVM1502\\Git\\ENVM1502-Catchment-model\\Data\\120_days_01310521.txt',
 'C:\\Users\\david\\Documents\\@@ Python\\Jaar 5\\Q3\\ENVM1502\\Git\\ENVM1502-Catchment-model\\Data\\2007-2010_01310521.txt']

In [22]:
pd.read_csv(files[0],delimiter="	",skiprows=[i for i in range(28)] + [29])

,agency_cd,site_no,datetime,tz_cd,106564_62619,106564_62619_cd,238970_62620,238970_62620_cd
0,USGS,1310521,2022-11-22 00:00,EST,-1.77,A,-2.91,P
1,USGS,1310521,2022-11-22 00:06,EST,-1.76,A,-2.90,P
2,USGS,1310521,2022-11-22 00:12,EST,-1.77,A,-2.91,P
3,USGS,1310521,2022-11-22 00:18,EST,-1.78,A,-2.92,P
4,USGS,1310521,2022-11-22 00:24,EST,-1.76,A,-2.90,P
...,...,...,...,...,...,...,...,...
28831,USGS,1310521,2023-03-22 03:06,EST,-1.44,P,-2.58,P
28832,USGS,1310521,2023-03-22 03:12,EST,-1.33,P,-2.47,P
28833,USGS,1310521,2023-03-22 03:18,EST,-1.23,P,-2.37,P
28834,USGS,1310521,2023-03-22 03:24,EST,-1.12,P,-2.26,P
28835,USGS,1310521,2023-03-22 03:30,EST,-1.01,P,-2.15,P

https://waterservices.usgs.gov/nwis/iv/?sites=01327750&parameterCd=00060&startDT=2023-03-15T05:45:18.716-04:00&endDT=2023-03-22T05:45:18.716-04:00&siteStatus=all&format=rdb